import { Command } from 'commander';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import chalk from 'chalk';
import { jsonToMermaid } from '../lib/json-to-mermaid.js';
import type { UxPathsDoc } from '../lib/types.js';

const HEADER = '%% AUTO-GENERATED by dfl-ux-paths — do not edit by hand.\n';

export function registerGenerateMermaid(program: Command): void {
  program
    .command('generate-mermaid [path]')
    .description('Generate a Mermaid graph from a flows.json file.')
    .option('-o, --out <file>', 'Output path (defaults to <dir>/flows.mmd).')
    .action((maybePath: string | undefined, opts: { out?: string }) => {
      const path = resolve(process.cwd(), maybePath || '.dfl-ux-paths/flows.json');
      if (!existsSync(path)) {
        console.error(chalk.red('File not found:'), path);
        process.exit(1);
      }
      const doc = JSON.parse(readFileSync(path, 'utf8')) as UxPathsDoc;
      const out = opts.out
        ? resolve(process.cwd(), opts.out)
        : resolve(dirname(path), 'flows.mmd');
      const body = HEADER + jsonToMermaid(doc);
      writeFileSync(out, body, 'utf8');
      console.log(chalk.green('Wrote'), out);
    });
}
